DELETE https://localhost:7127/api/WeatherForecast/39 HTTP/1.1
content-type: application/json

###
GET https://localhost:7127/api/WeatherForecast HTTP/1.1
content-type: application/json
###
GET http://localhost:4200/styles.css